import 'package:flutter_test/flutter_test.dart';
import 'package:procure_mate/models/site_manager.dart';
import 'package:procure_mate/screens/purchase_request_screen.dart';

void main(){
  double width=400;
  double height = 900;
  SiteManager user = SiteManager('E001', 'Saman', '0714256987', 'Saman@gmail.com', 'saman123', 'sitemanager', 'S001', 'Galle');
  test('Test the total generated by multiplying unit price and qty',(){
    //Step 1
    PurchaseRequestScreen PO = PurchaseRequestScreen(width,height,user);

    //Step 2





  });
}