const router = require("express").Router();
let Supplier = require("../models/Supplier");
let PurchaseOrder = require("../models/PurchaseOrder");
let Item = require("../models/Item");
let DeliveryNote = require("../models/DeliveryNote");
let Invoice = require("../models/Invoice");

// This backend route is used to get all suppliers from suppliers collection.
router.route("/").get((req, res) => {
  Supplier.find()
    .then((supplier) => {
      res.json(supplier);
    })
    .catch((err) => {
      console.log(err);
    });
});

// This backend route is used to get a specific supplier by email from suppliers collection.
router.route("/get/email/:email").get(async (req, res) => {
  let email = req.params.email;
  await Supplier.find({ email: `${email}` })
    .then((supplier) => {
      res.json(supplier);
    })
    .catch((err) => {
      console.log(err.message);
      res
        .status(500)
        .send({ status: "Error with get the supplier", error: err.message });
    });
});

// This backend route is used to get all the pending order related to a specific supplier.
router.route("/getpendingorders/:supplierid").get(async (req, res) => {
  let supplierId = req.params.supplierid;
  await PurchaseOrder.find({ supplierId: supplierId, status: "Approved" })
    .then((purchaseOrders) => {
      res.json(purchaseOrders);
    })
    .catch((err) => {
      console.log(err.message);
      res.status(500).send({
        status: "Error with get the purchase orders",
        error: err.message,
      });
    });
});

// This backend route is used to get all the invoices that have been generated by a specific supplier.
router.route("/getinvoices/:supplierid").get(async (req, res) => {
  let supplierId = req.params.supplierid;
  await Invoice.find({ supplierId: supplierId })
    .then((invoices) => {
      res.json(invoices);
    })
    .catch((err) => {
      console.log(err.message);
      res.status(500).send({
        status: "Error with get the invoices",
        error: err.message,
      });
    });
});

// This backend route is used to get all the delivery notes that have been generated by a specific supplier.
router.route("/getdeliverynotes/:supplierid").get(async (req, res) => {
  let supplierId = req.params.supplierid;
  await DeliveryNote.find({ supplierId: supplierId })
    .then((deliveryNotes) => {
      res.json(deliveryNotes);
    })
    .catch((err) => {
      console.log(err.message);
      res.status(500).send({
        status: "Error with get the delivery notes",
        error: err.message,
      });
    });
});

// This backend route is used to get a purchase order related to a specific supplier for the given purchase order number
router.route("/getorder/:supplierid/:pOrderId").get(async (req, res) => {
  let supplierId = req.params.supplierid;
  let pOrderId = "#" + req.params.pOrderId;
  await PurchaseOrder.find({ supplierId: supplierId, pOrderId: pOrderId })
    .then((purchaseOrder) => {
      res.json(purchaseOrder);
    })
    .catch((err) => {
      console.log(err.message);
      res.status(500).send({
        status: "Error with get the purchase order",
        error: err.message,
      });
    });
});

// This backend route is used to get the details of a given item name related to a specific supplier.
router.route("/getitem/:supplierid/:itemname").get(async (req, res) => {
  let supplierId = req.params.supplierid;
  let itemName = req.params.itemname;
  await Item.find({ supplierId: supplierId, itemName: itemName })
    .then((item) => {
      res.json(item);
    })
    .catch((err) => {
      console.log(err.message);
      res.status(500).send({
        status: "Error with get the item",
        error: err.message,
      });
    });
});

// This backend route is used to get the invoice for the given invoice id.
router.route("/getinvoice/:invoiceId").get(async (req, res) => {
  let invoiceId = "#" + req.params.invoiceId;
  await Invoice.find({ invoiceId: invoiceId })
    .then((invoices) => {
      res.json(invoices);
    })
    .catch((err) => {
      console.log(err.message);
      res.status(500).send({
        status: "Error with get the invoice",
        error: err.message,
      });
    });
});

// This backend route is used to get a delivery note for a given delivery note id.
router.route("/getdeliverynote/:deliveryId").get(async (req, res) => {
  let deliveryId = "#" + req.params.deliveryId;
  await DeliveryNote.find({ deliveryId: deliveryId })
    .then((deliveryNotes) => {
      res.json(deliveryNotes);
    })
    .catch((err) => {
      console.log(err.message);
      res.status(500).send({
        status: "Error with get the delivery note",
        error: err.message,
      });
    });
});

// This backend route is used to create a new delivery note.
router.route("/createdeliverynote").post((req, res) => {
  const deliveryId = req.body.deliveryId;
  const pOrderId = req.body.pOrderId;
  const supplierId = req.body.supplierId;
  const date = req.body.date;
  const status = req.body.status;
  const itemCode = req.body.itemCode;
  const itemName = req.body.itemName;
  const unitPrice = Number(req.body.unitPrice);
  const qty = Number(req.body.qty);
  const uom = req.body.uom;
  const siteMngId = req.body.siteMngId;
  const siteId = req.body.siteId;
  const location = req.body.location;

  // Create a new delivery note object
  const deliveryNote = new DeliveryNote({
    deliveryId,
    pOrderId,
    supplierId,
    date,
    status,
    itemCode,
    itemName,
    unitPrice,
    qty,
    uom,
    siteMngId,
    siteId,
    location,
  });

  // Save the delivery note object to the database
  deliveryNote
    .save()
    .then(() => {
      res.json("Delivery Note Added.");
    })
    .catch((err) => {
      console.log(err);
    });
});

// This backend route is used to create a new invoice.
router.route("/createinvoice").post((req, res) => {
  const invoiceId = req.body.invoiceId;
  const deliveryId = req.body.deliveryId;
  const pOrderId = req.body.pOrderId;
  const supplierId = req.body.supplierId;
  const itemCode = req.body.itemCode;
  const itemName = req.body.itemName;
  const qty = Number(req.body.qty);
  const uom = req.body.uom;
  const unitPrice = Number(req.body.unitPrice);
  const cost = Number(req.body.cost);
  const date = req.body.date;
  const paymentStatus = req.body.paymentStatus;

  // Create a new invoice object
  const invoice = new Invoice({
    invoiceId,
    deliveryId,
    pOrderId,
    supplierId,
    itemCode,
    itemName,
    qty,
    uom,
    unitPrice,
    cost,
    date,
    paymentStatus,
  });

  // Save the invoice object to the database
  invoice
    .save()
    .then(() => {
      res.json("Invoice Added.");
    })
    .catch((err) => {
      console.log(err);
    });
});

// This backend route is used to update a purchase order.
router.route("/updatepurchaseorder/:pOrderId").put(async (req, res) => {
  let pOrderId = "#" + req.params.pOrderId;
  const {
    itemCode,
    itemName,
    uom,
    date,
    dueDate,
    supplierId,
    siteMngId,
    siteId,
    location,
    status,
  } = req.body;
  const unitPrice = Number(req.body.unitPrice);
  const qty = Number(req.body.qty);
  const amount = Number(req.body.amount);

  // Updated purchase order object
  const purchaseOrder = {
    pOrderId,
    itemCode,
    itemName,
    unitPrice,
    qty,
    uom,
    amount,
    date,
    dueDate,
    supplierId,
    siteMngId,
    siteId,
    location,
    status,
  };

  // Update the purchase order in the database
  await PurchaseOrder.findOneAndUpdate({ pOrderId: pOrderId }, purchaseOrder)
    .then(() => {
      res.status(200).send({ status: "Purchase Order Updated" });
    })
    .catch((err) => {
      console.log(err);
      res.status(500).send({
        status: "Error with updating the purchase order",
        error: err.message,
      });
    });
});

// This backend route is used to delete a delivery note. This is used only for testing purposes.
router.route("/deletedeliverynote/:deliveryId").delete(async (req, res) => {
  let deliveryId = "#" + req.params.deliveryId;

  // Delete the delivery note from the database
  await DeliveryNote.findOneAndDelete({ deliveryId: deliveryId })
    .then(() => {
      res.status(200).send({ status: "Delivery note deleted" });
    })
    .catch((err) => {
      console.log(err.message);
      res.status(500).send({
        status: "Error with delete Delivery Note",
        error: err.message,
      });
    });
});

// This backend route is used to delete a specific invoice. This is used only for testing purposes.
router.route("/deleteinvoice/:invoiceId").delete(async (req, res) => {
  let invoiceId = "#" + req.params.invoiceId;

  // Delete the invoice from the database
  await Invoice.findOneAndDelete({ invoiceId: invoiceId })
    .then(() => {
      res.status(200).send({ status: "Invoice deleted" });
    })
    .catch((err) => {
      console.log(err.message);
      res.status(500).send({
        status: "Error with delete invoice",
        error: err.message,
      });
    });
});

module.exports = router;
