const ProcurementConstants = {
    //COMMON
    LOGOUT_BUTTON_TEXT: 'Logout',
    CURRENCY: 'Rs.',

    //NAVIGATION
    NAVIGATION_TAB1_NAME: 'Raised Orders',
    NAVIGATION_TAB2_NAME: 'Approved Orders',
    NAVIGATION_TAB3_NAME: 'Rejected Orders',
    NAVIGATION_TAB4_NAME: 'Direct Placed Orders',

    //TABLE HEADERS
    TABLE_HEADER_PO_ID: 'PO ID',
    TABLE_HEADER_ITEM_CODE: 'Item Code',
    TABLE_HEADER_ITEM_NAME: 'Item Name',
    TABLE_HEADER_QUANTITY: 'Quantity',
    TABLE_HEADER_UNIT_PRICE: 'Unit Price',
    TABLE_HEADER_REJECT_REASON: 'Reject Reason',
    TABLE_HEADER_DATE: 'Date',
    TABLE_HEADER_SITE: 'Site',

    // RAISED ORDERS PAGE
    RAISED_ORDERS_PAGE_TITLE: 'Requisition Approval',
    PROCUREMENT_STAFF_USER_ROLE: 'Procurement Staff',
    RAISED_ORDERS_PAGE_PAGE_BODY_HEADING: 'Raised Orders',
    RAISED_ORDERS_PAGE_PAGE_BODY_NO_ORDERS_MESSAGE: 'No Raised Orders',
    SINGLE_RAISED_ORDER_PAGE_PAGE_BODY_HEADING: 'Order',

    //SINGLE RAISED ORDERS PAGE 
    SINGLE_RAISED_ORDERS_PAGE_BODY_HEADING: 'Order Item Details',
    SINGLE_RAISED_ORDERS_PAGE_ORDER_LIMIT_VALUE: 200000,
    SINGLE_RAISED_ORDERS_PAGE_ORDER_PLACED_BY: 'Order Placed by',
    SINGLE_RAISED_ORDERS_PAGE_ORDER_PLACED_BY_NAME: 'Site Location',
    SINGLE_RAISED_ORDERS_PAGE_ORDER_PLACED_BY_DATE: 'Date',
    SINGLE_RAISED_ORDERS_PAGE_TABLE_HEADER_NAME: 'Name',
    SINGLE_RAISED_ORDERS_PAGE_TABLE_HEADER_QUANTITY: 'Quantity',
    SINGLE_RAISED_ORDERS_PAGE_TABLE_HEADER_UNIT_PRICE: 'Unit Price',
    SINGLE_RAISED_ORDERS_PAGE_TABLE_HEADER_TOTAL: 'Total',
    SINGLE_RAISED_ORDERS_PAGE_TABLE_GROSS_TOTAL: 'Gross Total',
    SINGLE_RAISED_ORDERS_PAGE_WARNING_MESSAGE: 'Order Limit exceeded! Reject Order',
    SINGLE_RAISED_ORDERS_PAGE_ORDER_LIMIT: 'Order Limit : ',
    SINGLE_RAISED_ORDERS_PAGE_REJECT_REASON: 'Reject Reason : ',
    SINGLE_RAISED_ORDERS_PAGE_APPROVE_BUTTON: '✔️ Approve',
    SINGLE_RAISED_ORDERS_PAGE_REJECT_BUTTON: '❌ Reject',
    SINGLE_RAISED_ORDERS_PAGE_REJECT_REASON_HINT: 'Enter reject reason...',

    // APPROVED ORDERS PAGE
    APPROVED_ORDERS_PAGE_TITLE: 'Approved Requisitions',
    APPROVED_ORDERS_PAGE_PAGE_BODY_HEADING: 'Approved Orders',
    APPROVED_ORDERS_PAGE_PAGE_BODY_NO_ORDERS_MESSAGE: 'No Approved Orders',

    // REJECTED ORDERS PAGE
    REJECTED_ORDERS_PAGE_TITLE: 'Rejected Requisitions',
    REJECTED_ORDERS_PAGE_PAGE_BODY_HEADING: 'Rejected Orders',
    REJECTED_ORDERS_PAGE_PAGE_BODY_NO_ORDERS_MESSAGE: 'No Rejected Orders',

    // DIRECT PLACED ORDERS PAGE
    DIRECT_PLACED_ORDERS_PAGE_TITLE: 'Direct Requisitions',
    DIRECT_PLACED_ORDERS_PAGE_PAGE_BODY_HEADING: 'Direct Placed Orders',
    DIRECT_PLACED_ORDERS_PAGE_PAGE_BODY_NO_ORDERS_MESSAGE: 'No Direct Placed Orders',

}

export default ProcurementConstants;