const ProcurementConstants = {
    //COMMON
    LOGOUT_BUTTON_TEXT: 'Logout',
    CURRENCY: 'Rs.',

    // RAISED ORDERS PAGE
    RAISED_ORDERS_PAGE_TITLE: 'Requisition Approval',
    RAISED_ORDERS_USER_ROLE: 'Procurement Staff',
    RAISED_ORDERS_TAB1_NAME: 'Raised Orders',
    RAISED_ORDERS_TAB2_NAME: 'Approved Orders',
    RAISED_ORDERS_TAB3_NAME: 'Rejected Orders',
    RAISED_ORDERS_TAB4_NAME: 'Direct Placed Orders',
    RAISED_ORDERS_PAGE_PAGE_BODY_HEADING: 'Raised Orders',
    RAISED_ORDERS_PAGE_PAGE_BODY_NO_ORDERS_MESSAGE: 'No Raised Orders',

    //RAISED ORDERS PAGE TABLE HEADERS
    RAISED_ORDERS_TABLE_HEADER_PO_ID: 'PO ID',
    RAISED_ORDERS_TABLE_HEADER_ITEM_CODE: 'Item Code',
    RAISED_ORDERS_TABLE_HEADER_ITEM_NAME: 'Item Name',
    RAISED_ORDERS_TABLE_HEADER_QUANTITY: 'Quantity',
    RAISED_ORDERS_TABLE_HEADER_UNIT_PRICE: 'Unit Price',
    RAISED_ORDERS_TABLE_HEADER_DATE: 'Date',
    RAISED_ORDERS_TABLE_HEADER_SITE: 'Site',
    SINGLE_RAISED_ORDER_PAGE_PAGE_BODY_HEADING: 'Order',

    //SINGLE RAISED ORDERS PAGE 
    SINGLE_RAISED_ORDERS_PAGE_BODY_HEADING: 'Order Item Details',
    SINGLE_RAISED_ORDERS_PAGE_ORDER_LIMIT_VALUE: 3000,
    SINGLE_RAISED_ORDERS_PAGE_ORDER_PLACED_BY: 'Order Placed by',
    SINGLE_RAISED_ORDERS_PAGE_ORDER_PLACED_BY_NAME: 'Site Location',
    SINGLE_RAISED_ORDERS_PAGE_ORDER_PLACED_BY_DATE: 'Date',
    SINGLE_RAISED_ORDERS_PAGE_TABLE_HEADER_NAME: 'Name',
    SINGLE_RAISED_ORDERS_PAGE_TABLE_HEADER_QUANTITY: 'Quantity',
    SINGLE_RAISED_ORDERS_PAGE_TABLE_HEADER_UNIT_PRICE: 'Unit Price',
    SINGLE_RAISED_ORDERS_PAGE_TABLE_HEADER_TOTAL: 'Total',
    SINGLE_RAISED_ORDERS_PAGE_TABLE_GROSS_TOTAL: 'Gross Total',
    SINGLE_RAISED_ORDERS_PAGE_WARNING_MESSAGE: 'Order Limit exceeded! Reject Order',
    SINGLE_RAISED_ORDERS_PAGE_ORDER_LIMIT: 'Order Limit : ',
    SINGLE_RAISED_ORDERS_PAGE_REJECT_REASON: 'Reject Reason : ',
    SINGLE_RAISED_ORDERS_PAGE_APPROVE_BUTTON: '✔️ Approve',
    SINGLE_RAISED_ORDERS_PAGE_REJECT_BUTTON: '❌ Reject',
    SINGLE_RAISED_ORDERS_PAGE_REJECT_REASON_HINT: 'Enter reject reason...'

}

export default ProcurementConstants;