const constants = {
  PENDING_ORDERS: "Pending Orders",
  PENDING_ORDER: "Pending Order",
  SUPPLIER: "Supplier",
  INVOICES: "Invoices",
  MY_DELIVERY_LOG: "My Delivery Log",
  LOG_OUT: "Log Out",
  PO_ID_DASH_HASH: "PO ID - #",
  DELIVERY_INFORMATION: "Delivery Information",
  DO_ID: "DO ID",
  DASH_HASH_D_DASH: "- #D-",
  REQUESTED_QUANTITY: "Requested Quantity",
  DELIVERED_QUANTITY: "Delivered Quantity",
  SITE_ID: "Site ID",
  LOCATION: "Location",
  ITEM_NAME: "Item Name",
  INVOICE_DETAILS: "Invoice Details",
  INVOICE_NO: "Invoice No",
  DASH_HASH_IN_DASH: "- #IN-",
  UNIT_PRICE: "Unit Price",
  RS_DOT: "Rs.",
  QUANTITY: "Quantity",
  TOTAL_AMOUNT: "Total Amount",
  PROCEED: "Proceed",
  INVISIBLE: "Invisible",
  PO_ID: "PO ID",
  AMOUNT: "Amount",
  DATE: "Date",
  DELIVERY_DATE: "Delivery Date",
  HASH_IN_DASH: "#IN-",
  NO_PENDING_ORDERS: "No Pending Orders",
  DUE_DATE: "Due Date",
  DELIVERY_NOTE: "Delivery Note",
  INVOICE: "Invoice",
  SESSION_KEY_SUPPLIER: "prMateReilppus",
  SESSION_KEY_SUPPLIER_ID: "supplierId",
  SESSION_KEY_SUPPLIER_NAME: "supplierName",
  BASE_URL: "http://localhost:8070",
  SUPPLIER_URL: "supplier",
  GET_ORDER_URL: "getorder",
  GET_ITEM_URL: "getitem",
  CONFIRM_MESSAGE_CREATING_DELIVERY_NOTE_AND_INVOICE:
    "Are you sure you want to proceed?\nThis process will create the invoice and send the delivery note.",
  HASH_D: "#D",
  HASH: "#",
  SENT: "Sent",
};

export default constants;
